### ISSUE TITLE
Can't install - missing from NPM

### ISSUE THREAD

**Issue by evoactivity** [miguelcobain/ember-yeti-table#1]
When trying to install the addon it fails as the addon cann't be found in NPM

```
error An unexpected error occurred: "https://registry.yarnpkg.com/ember-yeti-table: Not found".
```

**Comment by miguelcobain** [comment]
@evoactivity This addon isn't released yet!
Still need to do a couple of refactors and tests before I feel confident to release it.

Thanks for your interest, though.
The public API isn't likely to change, so if you'd like to give it a go you can still use it by installing from github:

```
npm install --save-dev ember-yeti-table
```
or
```
yarn add -D ember-yeti-table
```

I'm curious, how did you know about the addon?

**Comment by evoactivity** [comment]
Ahh, well that would make sense then!

Alex Speller mentioned it in the slack yesterday, I think he thought it had been released. I was just about to implement a table in my app and ember-light-table and ember-table are both overkill for what I need, alex mentioned this addon while talking to someone else about tables, I saw the message and I really liked the look of the template based api as it more closely matches my mental modal of what a table is so wanted to give it a try.

**Comment by miguelcobain** [comment]
> ember-light-table and ember-table are both overkill for what I need

> liked the look of the template based api as it more closely matches my mental modal of what a table is 

This is exactly why I created this addon. Hope you enjoy!

**Comment by miguelcobain** [comment]
@evoactivity version `0.0.1` was released. You should be able to install it normally now.
