### ISSUE TITLE
Make the sorting state logic configurable

### ISSUE THREAD

**Issue by Windvis** [miguelcobain/ember-yeti-table#10]
[This MR](https://github.com/miguelcobain/ember-yeti-table/issues/5) changed the way the click sorting behaves. I commented on that issue, but I'm not sure if that still notifies people after it is closed, so I'm opening this issue to discuss it.

What do you think about making this configurable somehow? It could be as simple as having a flag which toggles between the two versions. Or maybe a function argument which decides how to handle the click? That way the project can adjust the default behaviour if needed.

**Comment by miguelcobain** [comment]
@Windvis can you elaborate on why you don't want it to cycle through unsorted again? Or is it just a matter of preference?

**Comment by Windvis** [comment]
I don't have a source to back it up, but I think it feels weird, UX-wise. We always set a default sort on one of the columns (for ex, first name asc). When the user clicks multiple times he suddenly has an unsorted view, which can be confusing. The PM on the project already complained about a "bug", so at least he agrees with me :P

It might not be a (UX) problem if you don't use the default sorting option though. I haven't looked at other table components, so I'm not sure how they handle things. 

Anyway, having the choice would be sweet :)

**Comment by miguelcobain** [comment]
Datatables, for example, also doesn't go to the unsorted state.
I guess we should default to that but allow it to cycle to unsorted optionally.

Any API suggestions?

/cc @ctcpip

**Comment by ctcpip** [comment]
if you wanted to take inspiration from datatables, it's certainly one way of addressing the need...  

https://datatables.net/reference/option/columns.orderSequence

**Comment by miguelcobain** [comment]
@ctcpip excellent. We can have sortSequence. Both on the global table and on individual columns.

I noticed that they don't provide the unsorted States, right?

**Comment by ctcpip** [comment]
It appears that way, but I did not scrutinize the docs

**Comment by miguelcobain** [comment]
@ctcpip if you want to retain your current behavior, please use `@sortSequence="asc,desc,unsorted"`. Either on `<YetiTable>` or on any specific column `<header.column>`.

It accepts either a comma-separated list or an array. Refer to the sorting docs for more info.
