### ISSUE TITLE
Cannot supply data-* attribute bindings

### ISSUE THREAD

**Issue by ahawkins** [miguelcobain/ember-yeti-table#12]
I switched to `yeti-table` which replaced my raw HTML. I use `data-*` for tests. I tried a few solutions to patch this in but couldn't. I tried reopening the component to add in `attributeBindings` but that didn't work because tag-less components. I tried doing DOM hackery via `didInsertElement` but could not because `this.element` is undefined (again, tag-less component). 

I gave up and used class names for now. I would like some way to keep the test supporting markup out of the real stuff.

Have you considered some way to provide this or some way to override the layouts. I also attempted that but could not figure out how to import a template like done in addons.

**Comment by miguelcobain** [comment]
@ahawkins you should be able to use arbitrary attributes on any component on version `0.0.6`.
Please reopen if you find any issues.
