### ISSUE TITLE
Allow sorting and filtering to not observe changes in the data

### ISSUE THREAD

**Issue by cah-briangantzler** [miguelcobain/ember-yeti-table#149]
Most times having the table resort and filter to respect changes in the data is a good thing. I have a use case where it is not. I would like to do in-line editing. While typing in the input fields, I would not want the object to disappear if it no longer meets the filter, or move to a different page based on sort. Once the record is saved, I also would not want it to move, to allow the user to change their mind and edit again without having to search for it.

I still want sorting and filtering to work, based on the user clicking a column or entering a filter, just no longer observe.

I an thinking of a property on the table itself `@disableObserveData` that defaults to false, but could be set to true for my use case. Given my use case it is only needed at the table level and not at the column level. If you would like column as well let me know.

This sound ok for a PR?

**Comment by miguelcobain** [comment]
So, in your use case the table would sort/filter on first render but would never update afterwards, requiring some sort of refresh/rerender?

**Comment by cah-briangantzler** [comment]
Yes, it would sort/filter on initial render, sort when columns are clicked, filter when filter inputs are changed. Just NOT observe changes in data. Since I still want filtering and sort to work when the user specifically requests it, I cant just turn off filtering and sorting altogether

**Comment by miguelcobain** [comment]
Sounds like a good feature. :shipit:

**Comment by cah-briangantzler** [comment]
Its an easy change, will get that together shortly. Any comments on property name or is `disableObserveData` ok?   Will be doing table level only, not column level. Given the reason I want it turned off. I cant think of why I would want it column per column. (Although, LOL, column per column would have also solved the `@each` problem)

**Comment by miguelcobain** [comment]
The "observe" part feels like we're using observers, which is not really the case.

Perhaps an `@ignoreDataChanges={{true}}` that defaults to `false`?

**Comment by cah-briangantzler** [comment]
I didnt like the observe portion either, but I think thats technically whats happening, we arent setting observers but something is somewhere.

I like your property name better though. Will go with that
