### ISSUE TITLE
Allow for data attributes to be bound to elements

### ISSUE THREAD

**Issue by hbrysiewicz** [miguelcobain/ember-yeti-table#172]
Currently unable to bind `data-test-id` attributes to components for use in testing.

```
<row.cell @data-test-id="row-actions">
 ...
</row.cell>
```

Should probably be allowed for `data-test-id` since it is so widely used in the community for testing and being style-agnostic. Probably should also be setup for other data-like attributes. 

It does seem to work on:
- `<YetiTable>`
- `<table.body>`
- `<body.row>`

It does not work on:
- `<header.column>`
- `<row.cell>`

**Comment by cah-briangantzler** [comment]
I believe this is just applying ...attributes in the correct place. I have been playing with ember-sortable and will be applying modifiers to yeti-table components, ...attributes does this too. 

Working on another PR, was going to include this anyway. Will let you know

**Comment by cah-briangantzler** [comment]
So ignore that. Yeti is using component wrapper tags. Those are the ones working, however on the ones not using wrapper tags, ...attributes is applies, cell for example https://github.com/miguelcobain/ember-yeti-table/blob/master/addon/components/yeti-table/body/row/cell/template.hbs#L2

For those you if definitely have to remove the @ from data-test-id. Im surprised the @ is working though on the ones you say it is.

**Comment by miguelcobain** [comment]
@cah-briangantzler row.cell does forward ...attributes. shouldn't the case illustrated @hbrysiewicz work?

**Comment by miguelcobain** [comment]
Oh. @hbrysiewicz you need to use 
```hbs
<row.cell data-test-id="row-actions">
 ...
</row.cell>
```

Without the `@`. Can you confirm it works?

**Comment by cah-briangantzler** [comment]
:) Yea I said that above too. You just said it better

**Comment by hbrysiewicz** [comment]
@cah-briangantzler That doesn't actually work with the removal of `@` sign. It still does not pass through.

**Comment by miguelcobain** [comment]
@hbrysiewicz there is in fact a test that makes sure that it works: https://github.com/miguelcobain/ember-yeti-table/blob/master/tests/integration/components/yeti-table/general-test.js#L565-L606

**Comment by hbrysiewicz** [comment]
@miguelcobain I think it must be an ember version thing. The project I'm working on is in 3.4 still and I see the `ember-try` config only specifies 3.8 and up... I pulled down a copy and tried running tests with 3.4 and they failed for several other reasons of course. So :( sad face. We will just have to update. Thanks 👍

**Comment by miguelcobain** [comment]
You could try using https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill

Not sure if addons will be affected. Best of luck!

**Comment by hbrysiewicz** [comment]
For anyone finding themselves here - the above polyfill did the trick 👍
