### ISSUE TITLE
Add a "Dumb" Table mode

### ISSUE THREAD

**Issue by Windvis** [miguelcobain/ember-yeti-table#18]
A while ago we talked about a 'dumb' variation of the current YetiTable component. 

Data fetching / sort handling (and state) / pagination would be handled outside of the YetiTable component. YetiTable would only be used display the data.

Do you still think this is something you want to add to this addon? I imagine this will makes things a lot more complex, but I'm unfamiliar with the source code.

If not I'll probably create a simplified version myself, but I would rather not have to add another table addon 😄 .

**Comment by miguelcobain** [comment]
@Windvis can you remind me (and to keep it documentos here) why doesn't just using `@data` is not enough for your needs?

You would update `@data` outside yeti-table and it should reflect those chances.

**Comment by Windvis** [comment]
Yes. It's been a while since I tried that, but I believe the bottleneck was the sorting. We would need a way to link actions to sorting events so that our code knows when to refetch data. I assume the same is needed for the pagination.

We worked around it by using loadData, but that isn't ideal.

**Comment by miguelcobain** [comment]
I see.
We could add some actions that trigger when sorting changes and do the same for pagination.
Do you think that would solve this problem?

**Comment by Windvis** [comment]
I think that is all that is needed for the sorting (which is all we use in our apps), but I'm not 100% it will suffice for the pagination.

I think we would also need to be able to pass in more pagination info to YetiTable, right?

For ex:
For example, we have 100 records, our server paginates with 20 items per page and we are currently on page 3. Yeti somehow needs to know this or the pagination wouldn't make sense.

The docs only mention a @pageSize argument at the moment, so I think we would need `@totalItems` and` @activePage` arguments to make the pagination work as well. But I might be missing something :)

**Comment by cah-briangantzler** [comment]
So basically we are looking at a server paginated table right? 

Filtering would also play a role as it would change the records displayed on any page.

Rather than just add a bunch of parameters, should we look at it from the bigger picture of a server side paginated feature, and build the best API for that?

**Comment by miguelcobain** [comment]
@cah-briangantzler I think our `@loadData` does the job very well for server-paginated/sorted/filtered table, no?

OP seems to want to completely opt-out of yeti-table "behavioral" features and just use it to render html.
But that raises a good question. @Windvis why didn't `@loadData` fit your needs?

**Comment by Windvis** [comment]
Yea, sure. I haven't been following the latests development, so I'm not sure what changed. I assumed filtering wouldn't be a problem, since that can be handled outside of YetiTabe (Yeti would simply display the filtered data).

But you are correct, I would like to make server paginated / sorted / filtered data a first class citizen of YetiTable.

We never use client side only tables in our apps and most of our views have an alternative layout for mobile devices (which use the same data). At the moment we can work around this by using YetiTable's loadData, but it isn't optimal :-D

**Comment by miguelcobain** [comment]
> `loadData` assumes that YetiTable fetches the data

When you opt into using `@loadData`, you are the one responsible for fetching the data in the loadData function. You can use ember-data, ajax, fetch, whatever you need to. yeti table just triggers that function.

**Comment by cah-briangantzler** [comment]
LOL, to be fair, I haven't read up on loadData. I was in the middle of typing up an alternate proposal, jumped over to read loadData and it was basically what I was going to purpose.

**Comment by Windvis** [comment]
I guess I'm not very good at explaining things.

We already use loadData to work around this problem. It just isn't an ideal solution. 

> loadData assumes that YetiTable fetches the data

What I meant with that is that the intent to fetch data is still triggered by YetiTable. We can't do this in another component and "reuse" the data in YetiTable. Since our projects have also have a mobile view we have to effectively double the data fetch logic, once for the mobile view, and once for YetiTable's loadData. 

Another downside of this is that we have to pass through all 'dependentKeys' that need to be watched to trigger loadData to YetiTable through the @filterUsing argument. This is counter intuitive, since those things have nothing to do with the table component.

Like I said before, we can work around the issues by using @loadData, but it is not ideal and feels hacky. I assume you guys haven't actually tried something similar before or you would come to the same conclusion.

Anyway, I'm not forcing you to add new things to YetiTable. I'm perfectly fine with not wanting to expand the public api for use cases that might not be useful to a lot of people. I also wouldn't mind making a new table addon which fits our use-case.

**Comment by cah-briangantzler** [comment]
What Im getting they want to feed the data through @data (outside source) and tell Yeti how many pages there are, not respond to an action (loadData).

I would think that they should do the following.
- DO not use yeti filtering
- Do not use yeti pagination (unless you are providing more than one page in data, then use pagination, and set pageNumber
- Do not use yeti pagination control (write your own (Or make the pagination control more configurable)

This just leaves sorting which I is how you started this thread off, provide an onSort action

From what I understand this should do what they are asking for

**Comment by Windvis** [comment]
I think it's better to not add this to YetiTable and keep it focused on client side tables.

**Comment by cah-briangantzler** [comment]
I would have liked the addition of some sort triggers. :)
