### ISSUE TITLE
header and body in block usage result duplicate row rendering

### ISSUE THREAD

**Issue by vihai** [miguelcobain/ember-yeti-table#2]
Hello,

I'm using YetiTable with both headers and body in block format. It looks like the rows are rendered twice, first, as expected, as row.cell contents, then as the result of specifying table.headers.

This is my template, the data is currently the static result of a ember-data query:

```
  <YetiTable @data={{model}} class="ui selectable celled table" as |table|>
    <table.header as |header|>
      <header.column>
        Tipo
      </header.column>
      <header.column>
        Identificatore
      </header.column>
      <header.column>
        Scadenza
      </header.column>
    </table.header>

    <table.body as |body data|>
      <body.row as |row|>
        <row.cell>
          {{data.type}}
        </row.cell>
        <row.cell>
          {{data.identifier}}
        </row.cell>
        <row.cell>
          {{if data.valid_to (moment-format data.valid_to 'DD-MM-YYYY')}}
        </row.cell>
      </body.row>
    </table.body>
    <table.body/>
  </YetiTable>
```

This is the result:

![screenshot1](https://user-images.githubusercontent.com/202039/46965682-d0734380-d0ab-11e8-845f-d5986fa4e702.png)

Giving a very shallow look at the code it seems that in addon/components/yeti-table/body/template.hbs hasBlock is not set ever. Am I wrong?

**Comment by miguelcobain** [comment]
@vihai the reason the rows are rendered twice is because you're rendering the table body twice. First you render them using:

```hbs
    <table.body as |body data|>
      <body.row as |row|>
        <row.cell>
          {{data.type}}
        </row.cell>
        <row.cell>
          {{data.identifier}}
        </row.cell>
        <row.cell>
          {{if data.valid_to (moment-format data.valid_to 'DD-MM-YYYY')}}
        </row.cell>
      </body.row>
    </table.body>
```

and then using 

```hbs
<table.body/>
```

Removing `<table.body/>` should fix the problem, right?

**Comment by miguelcobain** [comment]
Glad it's working correctly. 

The `hasBlock` property is true when the component is invoked with a block.
It's a feature of Ember components. Recently it was replaced with the `has-block` helper to make it less confusing: https://guides.emberjs.com/release/components/block-params/#toc_supporting-both-block-and-non-block-component-usage-in-one-template

But `hasBlock` still works.

Closing this now. :)
