### ISSUE TITLE
should rowClass be deprecated

### ISSUE THREAD

**Issue by cah-briangantzler** [miguelcobain/ember-yeti-table#21]
rowClass was implemented to allow `<table.body />` (non-block form), Block form the body/row could have easily been added to the `<body.row>`.   Given that row is in themes, the same can now be accomplished as 
```
<YetiTable @theme={{hash row="rowClassName"}} />
```

Even better, the row class can now be specified in the config for all yeti tables or a reusable user theme instead of using rowClass on the component proper.

**Comment by miguelcobain** [comment]
Indeed, `@theme` seems like a superior abstraction to place this class.
I vote in favor of deprecating `@rowClass`.

**Comment by cah-briangantzler** [comment]
Ill see if I can throw together a PR for this as well.

**Comment by miguelcobain** [comment]
Removed `@rowClass` from documentation on master.
