### ISSUE TITLE
Enable some of the Table Properties in the config

### ISSUE THREAD

**Issue by cah-briangantzler** [miguelcobain/ember-yeti-table#22]
Some of the properties that can be passed into the table may be values that you would want on every table in your application. Since we have implemented the theme on the config, could some of these values also be on the config?

For example, the sortSequence. I would like it to be ['asc'. 'desc'. 'unsorted'] on every table in my application, would like to avoid defining and passing the parameter every place I use the yeti-table..

Would you be opposed to putting this (and possibly others) on the config with the theme (No in the theme)

Was also curious, sortSquence doesnt have optional in the argument definition, I thought that had to be there to make it options, or is the fact that you assign a default value make it optional? I note that sortable has a default and optional. Just wondering how optional and required arguments are actually suppose to be defined (since they removed @required)

**Comment by miguelcobain** [comment]
> Would you be opposed to putting this (and possibly others) on the config with the theme (No in the theme)

I think the theme is a bad place to put this, but having those on the global config would be nice!
What properties do you have in mind?

> Was also curious, sortSquence doesnt have optional in the argument definition, I thought that had to be there to make it options, or is the fact that you assign a default value make it optional? I note that sortable has a default and optional. Just wondering how optional and required arguments are actually suppose to be defined (since they removed @required)

Indeed, `sortable` had an unnecessary `optional` type. I removed it in https://github.com/miguelcobain/ember-yeti-table/commit/329f35d0d5032bc45d6bbd91b2ef3073a48bec0b and all tests are green.
Yes, if you supply a default value, you don't need `optional`, unless you really expect users to pass in undefined or null as valid values (might make sense in some cases).
For example, having a null/undefined `sortSequence` doesn't make sense, hence the type being non-optional.

**Comment by cah-briangantzler** [comment]
Yes, it would NOT be part of the theme, I mean where the theme is also defined.

I did not look at other properties, this is just the one we would like at this time, but if we are doing to do it, should probably have some others.

The reason I asked about the optional is that in order to default it from the config I can not longer have a default as defined on the property, so will need to add the optional. Let me look when I get a chance and see what others might make sense

**Comment by miguelcobain** [comment]
closed by #27
