### ISSUE TITLE
defining config without `theme` key errors

### ISSUE THREAD

**Issue by sumeetattree** [miguelcobain/ember-yeti-table#24]
Currently this line:
https://github.com/miguelcobain/ember-yeti-table/blob/329f35d0d5032bc45d6bbd91b2ef3073a48bec0b/addon/components/yeti-table/component.js#L316-L317
throws:
```js
TypeError: Cannot convert undefined or null to object
```
Maybe we can assert that a toplevel key `config.theme` is defined?

**Comment by miguelcobain** [comment]
Defining a theme in the config should be completely optional.
I didn't get that error in the dummy app. Did you add any config in your app?

**Comment by cah-briangantzler** [comment]
Im thinking the line should be 
```
let configTheme = config && config.theme ? config.theme : {} ;
```

when it executes the following line, config.theme could be undefined, the merge.all is having the problem.

Alternately you could do this
```
let configTheme = config ? config.theme :  undefined;
let mergedTheme = merge.all([{}, DEFAULT_THEME, configTheme || {}, this.get('theme') || {}]);
```

Which might make more sense since we are doing the `|| {}` on the `this.get("theme")` as well

**Comment by sumeetattree** [comment]
Yeah, I added this config:

```js
    'ember-yeti-table': {
      table: 'table',
      sorting: {
        columnSortable:  'table-sortable',
        columnSorted: 'table-sorted',
        columnSortedAsc: 'table-sorted-asc',
        columnSortedDesc: 'table-sorted-desc',
      },

      pagination: {
        controls: 'table-pagination-controls',
        info: 'table-pagination-controls-page-info',
        pageSize: 'table-pagination-controls-page-size',
        next: 'table-pagination-controls-next',
        previous: 'table-pagination-controls-previous'
      }
    }
```

Notice the missing `theme` key at the top level. This is mostly an ease of use scenario. I think you should assert for it in case devs miss the said key

Adding the missing `theme` key fixed it.

**Comment by cah-briangantzler** [comment]
Asserting it requires that the theme be specified in the config and that should be optional. Im not sure we want an assert there.

**Comment by miguelcobain** [comment]
@sumeetattree the reason we can't do that is because a user might want to define other configs *that aren't* the theme in the future.

For example, in #22 we're thinking about being able to define a `sortSequence` property in the config. Defining it without defining a `theme` should be a completely valid use case, so we shouldn't assert.

I'm totally in favor of making this more explicit in the documentation, though.

**Comment by sumeetattree** [comment]
> Im thinking the line should be
> 
> ```
> let configTheme = config && config.theme ? config.theme : {} ;
> ```
> when it executes the following line, config.theme could be undefined, the merge.all is having the problem.
> 
> Alternately you could do this
> 
> ```
> let configTheme = config ? config.theme :  undefined;
> let mergedTheme = merge.all([{}, DEFAULT_THEME, configTheme || {}, this.get('theme') || {}]);
> ```
> Which might make more sense since we are doing the `|| {}` on the `this.get("theme")` as well

@miguelcobain I get that totally.

We could improve the documentation. I would suggest adding an example in the documentation showing how to include the config from `/config/environment.js`. I had to dig through the source to find out it's even possible to do that.

**Comment by sumeetattree** [comment]
@miguelcobain  Let me know if you'd like a pull request with the documentation change.

**Comment by miguelcobain** [comment]
![screen shot 2019-02-07 at 15 54 45](https://user-images.githubusercontent.com/631691/52423802-b8a74b80-2af0-11e9-8227-9c8ee52d3377.png)

@sumeetattree @cah-briangantzler I wrote this up and am about to push it to master. Let me know if something isn't clear.

**Comment by sumeetattree** [comment]
@miguelcobain This looks good!

**Comment by cah-briangantzler** [comment]
I think this looks good
