### ISSUE TITLE
Couldn't find match for "escape-backticks" 

### ISSUE THREAD

**Issue by cah-briangantzler** [miguelcobain/ember-yeti-table#26]
Attempting to do a pull request and getting this when attempting yarn off the master branch

**Comment by cah-briangantzler** [comment]
Ahh, this is in your package.json on the master branch

```
 "ember-cli-addon-docs": "miguelcobain/ember-cli-addon-docs#escape-backticks",
```

**Comment by miguelcobain** [comment]
Should be fixed on master.
