### ISSUE TITLE
Assertion Failed: fullName must be a proper full name

### ISSUE THREAD

**Issue by abhilashmurthy** [miguelcobain/ember-yeti-table#266]
I'm getting this weird error when declaring YetiTable in my hbs files
```
Assertion Failed: fullName must be a proper full name
```

 Even something as simple as this doesn't work:
```
<YetiTable @data={{this.data}} as |t|>
  <t.header as |h|>
    <h.column @prop="firstName">
      First name
    </h.column>
    <h.column @prop="lastName">
      Last name
    </h.column>
    <h.column @prop="points">
      Points
    </h.column>
  </t.header>
  <t.body/>
</YetiTable>
```

Tried googling and using the stackoverflow answers, but none of them work. This is strangely happening only on YetiTable, and no other components of mine. Ember v3.5.0~.

Is there a simple fix to this I might have missed?

**Comment by abhilashmurthy** [comment]
I have reverted to version `v1.0.0` to fix this issue. Have a gut feeling that the feature introduced in v1.2.0 `@renderTableElement={{false}}` which renders the table outside of the component may be causing this error for me 🤔

**Comment by miguelcobain** [comment]
Thanks for reporting.

Does it work if you install `ember-angle-bracket-invocation-polyfill`?

https://github.com/ember-polyfills/ember-angle-bracket-invocation-polyfill

**Comment by miguelcobain** [comment]
Please reopen if still an issue.
