### ISSUE TITLE
Feature: Yeti Freeze (or no reactive sorting/filtering)

### ISSUE THREAD

**Issue by cah-briangantzler** [miguelcobain/ember-yeti-table#269]
Which is hilarious since its yeti.

We are trying to do inline editing, and it works great except, while editing if there is a sort or filter in effect the record moved. We can fix some of that by using changeset, but we are also doing an in-line add of a new record and changeset wont help there with sorting and filtering.

So I thought, if there was a way to just tell yeti freeze, temporarily ignore clicks on headers for sorting, filtering and other things along those lines, I could freeze when editing and unfreeze when saved. Wanted to see what you thought before exploring creating a PR.

The other alternative would be to provide a way to tell yeti NOT to reactive sort and filter. ONLY sort when the user clicks a column, ONLY filter when the filter changes.  I kinda like this option as well. (if there isnt already a way to do that, I seem to recall thinking about this before)

**Comment by cah-briangantzler** [comment]
LOL I thought this might have been available `@ignoreDataChanges={{true}}`

**Comment by miguelcobain** [comment]
A very nice folk once PRed that feature https://github.com/miguelcobain/ember-yeti-table/pull/151

😂

**Comment by cah-briangantzler** [comment]
Yea, I had a feeling it was me.
