### ISSUE TITLE
Inconsistent paginationData.totalRows

### ISSUE THREAD

**Issue by sly7-7** [miguelcobain/ember-yeti-table#282]
Hello, 

I basically wanted to render the pagination component both before and after the table, this way the user can eventually change page without scrolling. But I encounter a pretty weird issue. I will try to update this issue with a twiddle tomorow, for now I just have some screen shot demonstrating the issue.
The template calling the yeti-table is: 

```hbs
<YetiTable
  @data={{@model}}
  @ignoreDataChanges={{true}}
  @pagination={{true}}
  @pageSize={{25}}
as |table|>
    <table.thead as |head|>
      <head.row>
        <table.pagination/>
      </head.row>
    </table.thead>

   {{!- filters in header-}}

   {{!- body -}}

  <table.tfoot>
    <table.pagination/>
  </table.tfoot>

</YetiTable>
```

As result, when filtering, the paginationData is somehow out of sync
![Capture d’écran 2020-08-06 à 17 49 21](https://user-images.githubusercontent.com/1826661/89552965-2da23100-d80d-11ea-9232-1cc2c8c3451d.png)

And then emptying the filter.

![Capture d’écran 2020-08-06 à 17 49 49](https://user-images.githubusercontent.com/1826661/89552998-3c88e380-d80d-11ea-95c4-bdf751976dfe.png)

I've done some other experiments, where I use `{{table.paginationData.totalRows}}`, and it seems like before the second cell in the header, it is out of sync, and after, it has the right value.

**Comment by sly7-7** [comment]
As a workaround-hack, I double render the pagination component at the end of the table, but wrapped in a `{{#in-element}}` helper

**Comment by miguelcobain** [comment]
@sly7-7 if you're still interested in this use case, it would be great if you could submit a failing test, and we could start from there.

**Comment by sly7-7** [comment]
@miguelcobain Yes I will try to make that test (or at least a twiddle). I'll look at this tomorrow morning (9-12 AM GMT+1).

**Comment by sly7-7** [comment]
@miguelcobain Well, I can't reproduce it for now. I will test again in my app, and will come back. I'm closing for now.
