### ISSUE TITLE
Get initial sort/filter/pagination from queryParams

### ISSUE THREAD

**Issue by MichalBryxi** [miguelcobain/ember-yeti-table#34]
I'm using server-side sort/filter/pagination, so I'm using `loadDataTask()`. All works nice and well until I try to wire `queryParams` and default sorting (let's use sorting for example). On full page reload, the `loadDataTask` is called and with some additional logic might recognise that we're in full page reload and instead of using the arguments provided for the task, it will use `queryParams` for sorting. This will however not update the inner state of `yeti-table` and the respective classes on the headers won't be applied. 

```#js
// imports
export default Controller.extend({
  queryParams: ["sort"],
  sort: 'name',

  loadDataTask: task(function*({ sortData }) {
    yield timeout(250);

    if (!isEmpty(sortData)) {
      this.setProperties({
        sort: sortData
          .map(s => `${s.direction === "desc" ? "-" : ""}${s.prop}`)
          .join(","),
      });
    }

    let params = {
      sort: this.sort,
    };
    let posts = yield this.store.query("post", params);

    return posts;
  }).restartable()
});
```

Is there a way to achieve that? Easily?

**Comment by jelhan** [comment]
I've a similar requirement as also needing a way to control sorting from parent context. For me it's a user interaction done outside of the table that should alter the sorting. A simplified example would be a button "sort table by age" that is outside of `<form>` element.

The real-world use case is of course more complex. I have an input field, which allows user to enter a reference location. If provided the distance to that location is shown as an additional column in table. For a good user experience the table should be sorted automatically by that column when user enters a reference location the first time. If I didn't missed something, this is currently not supported.

**Comment by villander** [comment]
@MichalBryxi any news here?

**Comment by MichalBryxi** [comment]
I have not looked into this for a _long_ time, but ember-yeti-table got [quite a few arguments to loadData()](https://miguelcobain.github.io/ember-yeti-table/docs/async) and it feels like if you'd pass down `sortData` correctly, it should work?

See the example on that doc page which sort-of does exactly this. I actually think this issue is resolved and should be closed?
