### ISSUE TITLE
Async pagination with unknown totalRows

### ISSUE THREAD

**Issue by charlesfries** [miguelcobain/ember-yeti-table#387]
Is it possible to use the pagination features of this addon with a dataset of unknown size? I'm essentially trying to use the Prev/Next buttons sans the total entries count. Can I pass in my own values to enable/disable the pagination buttons myself?

**Comment by cah-briangantzler** [comment]
All the pagination data is yielded, so your worst case you could always write your own. 

The pagination control takes a parameter of paginationData. This is provided in the default control from yeti, but you can always override it 
```
   <row.cell colspan={{table.visibleColumns.length}}>
        <table.pagination @paginationData={{this.myData}}/>
      </row.cell>
```

Pagination data is an object that should have the following properties
```
{ 
    pageSize, 
    pageNumber, 
    pageStart, 
    pageEnd, 
    isFirstPage, 
    isLastPage, 
    totalRows, 
    totalPages 
}
```

Hope that gets you a start of where you need to go
