### ISSUE TITLE
Hasblock usage in 1.7.1 results in error with ember 4

### ISSUE THREAD

**Issue by bracke** [miguelcobain/ember-yeti-table#445]
Hi 

Version 1.7.1 still uses hasBlock, which should be replace with has-block. 
This results in an error with Ember v4.1.

It is fixed in the master branch.
I guess I'm asking for a new release which includes this change.

Kind regards
Bent Bracke

**Comment by charlesfries** [comment]
+1 @miguelcobain

**Comment by miguelcobain** [comment]
`master` is actually not what is released right now. `master` is in a process of updating to glimmer components that didn't quite finish yet. `v1` branch was what was released. `master` will become v2 when the migration is finished.
I released the `has-block` change as `1.7.2`. Please reopen if you see any other problems. Thanks for reporting.
