### ISSUE TITLE
Change/translate the text in the pagination

### ISSUE THREAD

**Issue by bracke** [miguelcobain/ember-yeti-table#446]
Hi 

I would like to change the text used by the pagination controls component.
Is this possible?

Kind regards
Bent Bracke

**Comment by cah-briangantzler** [comment]
I dont think it is. We wrote our own pagination component and do not use one provided. That doesnt work so well if you are just using `<table.body />` but we dont anywhere. All the data is provided to make that easy.

**Comment by bracke** [comment]
Sure, but the one provided could easily be extended to support it. Just take in the text as attributes.

**Comment by miguelcobain** [comment]
@bracke the included pagination component is really nothing special and it is totally optional.
But I guess it wouldn't hurt to provide more flexibility to it, making it accept some new arguments.

Not sure how you would deal with this line:
```hbs
Showing {{@paginationData.pageStart}} to {{@paginationData.pageEnd}} of {{@paginationData.totalRows}} entries
```

I will consider a PR for this, yes. 👍

**Comment by bracke** [comment]
Excellent. 
I will put my thinking cap on.
