### ISSUE TITLE
Could not find module `@ember-decorators/object/computed` due to older ember-decorators

### ISSUE THREAD

**Issue by sumeetattree** [miguelcobain/ember-yeti-table#51]
Hi, do you have plans to update the dependency on ember-decorators to the latest 6.0? I see that a pull request is already open here https://github.com/miguelcobain/ember-yeti-table/pull/40 .

This is currently preventing me from using `ember-decorators` with `ember-cli-decorator-polyfill` as ember complains with this error (in the browser):
```js
Uncaught Exception: 
 Error: Could not find module 
`@ember-decorators/object/computed` imported from 
`ember-yeti-table/components/yeti-table/component`
```
The 6.0 decorators have removed all the decorators that are available through the polyfill.
I had to pin the `@ember-decorators` to `6.0` to prevent it from failing due to other errors.

Let me know if and how I can help. Thanks!

**Comment by miguelcobain** [comment]
Thanks for reporting. This update has been on my radar for sometime.

Yeti-table uses `@ember-decorators/argument`, which still uses stage 2 decorators.
There's a pending PR there to revert to stage 1. When that is merged, we should be able to update yeti-table very easily.

Sorry for the hassle. Being an early adopter of decorators had its downsides.

**Comment by sumeetattree** [comment]
Not a problem. I'll try reverting back to the version in yeti-table and see if I can get away with it while we wait it out.

**Comment by miguelcobain** [comment]
Can you try depending on `miguelcobain/ember-yeti-table#master` to see if it fixes the problem?

Make sure to check the [CHANGELOG](https://github.com/miguelcobain/ember-yeti-table/blob/master/CHANGELOG.md) to know of all the breaking changes and exactly what happened.

This will be the `v1.0.0` soon.
