### ISSUE TITLE
runLoadData is not called when sorting the content

### ISSUE THREAD

**Issue by Windvis** [miguelcobain/ember-yeti-table#6]
Hey! Nice addon. Awesome job! I love the template based approach.

I'm experimenting with it a bit and I think that the @loadData argument function is not called when clicking on one of the table headers. Or am I just missing something? 😁

**Comment by miguelcobain** [comment]
@Windvis you are indeed correct, sir. This was a bug.
Not sure how it slipped through. I fixed it and added a test to make sure we don't regress.
