### ISSUE TITLE
Table headers always get the role="button" attribute even when they are not clickable

### ISSUE THREAD

**Issue by Windvis** [miguelcobain/ember-yeti-table#8]
I noticed that the table headers always have the role attribute set to button even when @sortable={{false}}. It looks like [this is hardcoded](https://github.com/miguelcobain/ember-yeti-table/blob/fb0c0c06c45bade9e997de486508da957996482e/addon/components/yeti-table/header/column/template.hbs#L3). Might be better to do this based on the @sortable state?

**Comment by miguelcobain** [comment]
Well, it is still a button, but it is disabled.
I guess the correct thing to do would be to add `aria-disabled` when sortable is false.

**Comment by Windvis** [comment]
Not sure if I agree with them still being buttons, but I'm no semantics expert 😁. Thanks for the swift follow-up!

**Comment by miguelcobain** [comment]
I see what you mean.

It's pretty common to write css like:
```css
button, [role=button] {
  cursor: pointer;
}
```

Stopping being a button is probably more appropriate.
