### ISSUE TITLE
Link to the documentation website in the readme is broken

### ISSUE THREAD

**Issue by Windvis** [miguelcobain/ember-yeti-table#9]
The readme links to the documentation website, but clicking that link results in a white page. It seems that linking to the docs without version info in the url causes a lot of 404 errors.

I don't know enough the documentation addon to know if that is supposed to work or not 😁.

**Comment by miguelcobain** [comment]
Thanks for reporting. This is related to https://github.com/ember-learn/ember-cli-addon-docs/issues/238

I fixed the assets path manually.
