### ISSUE TITLE
Pagination not rendered when first column is not visible

### ISSUE THREAD

**Issue by hannahrstannard** [miguelcobain/ember-yeti-table#98]
Given the example here (https://miguelcobain.github.io/ember-yeti-table/docs/pagination), if I were to make the first name column not visible, then the pagination disappears.

The yeti-table/foot/row/cell/template.hbs checks to see if the column is visible. When you do `colspan={{table.visibleColumns}}` and the first column is not visible, then pagination will not display.

**Comment by miguelcobain** [comment]
@hannahrstannard This was just in time for the `v1.0.0` release.

You can now use:
```hbs
<row.cell @visible={{true}} colspan={{table.visibleColumns.length}}>
  ...
</row.cell>
```

The `@visible={{true}}` here is used to always render the cell, even if that column is hidden.
Basically all the cell components now accept a `@visible` argument. Documentation was also updated to reflect this "trick".

Just a reminder that you can still place the pagination outside of the table tag. See this: https://miguelcobain.github.io/ember-yeti-table/docs/styling#pagination-controls-outside-the-table-element

There were some breaking changes on this version (hopefully nothing major). Check out the [changelog](https://github.com/miguelcobain/ember-yeti-table/blob/master/CHANGELOG.md) for more info.

Please reopen if you still have this issue.
